# Generated by Django 3.0.1 on 2020-10-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleTitle', models.CharField(blank=True, max_length=60, null=True)),
                ('ArticleBodyText', models.TextField(blank=True, max_length=10000, null=True)),
                ('ArticleKeywords', models.CharField(blank=True, max_length=500, null=True)),
                ('ArticleSlug', models.SlugField(max_length=255, unique=True)),
                ('ArticlePublishedDate', models.DateTimeField(auto_now_add=True)),
                ('ArticleUpdatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'articlesmodel',
                'ordering': ('ArticleTitle',),
            },
        ),
        migrations.CreateModel(
            name='UsersSearchQueriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userQuery', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('userIp', models.CharField(blank=True, max_length=200, null=True)),
                ('userEmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'usersqueriesmodel',
            },
        ),
    ]
