# Generated by Django 3.0.1 on 2021-03-07 10:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicsection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='ArticleImage',
            field=models.ImageField(blank=True, null=True, upload_to='ArticleImages'),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='ArticleBodyText',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
